### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by beta992** [STLVNUB/CloverGrower#10]
Building ... /Users/francois/Documents/CloverGrower/src/edk2/MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf [IA32]
Building ... /Users/francois/Documents/CloverGrower/src/edk2/MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull.inf [IA32]
/bin/sh: /Users/francois/Documents/CloverGrower/toolchain/ia32/gcc: No such file or directory
make: **\* [/Users/francois/Documents/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC48/IA32/MdePkg/Library/BasePcdLibNull/BasePcdLibNull/OUTPUT/PcdLib.obj] Error 127

build.py...
 : error 7000: Failed to execute command
    make tbuild [/Users/francois/Documents/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC48/IA32/MdePkg/Library/BasePcdLibNull/BasePcdLibNull]

build.py...
 : error 7000: Failed to execute command
    make tbuild [/Users/francois/Documents/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC48/IA32/MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull]

build.py...
 : error F002: Failed to build module
    /Users/francois/Documents/CloverGrower/src/edk2/MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf [IA32, GCC48, RELEASE]
- Failed -
  Build end time: 13:12:58, May.24 2013
  Build total time: 00:00:02

CloverGrower V5.1f Cloveria32 RELEASE  ERROR!!
Good Afternoon.

The strange part is why it wants to compile x32, I'm running x64. Anyway hope you can take a look at it. *I have already removed CloverGrower, and git clone again

**Comment by STLVNUB** [comment]
Looks like GCC not installed, if this is new build where is GCC 4.8.0 compile info??

**Comment by beta992** [comment]
-  gcc-4.8.0 extract...
-  gcc-4.8.0 extracted
-  gcc-4.8.0 configure...
-  gcc-4.8.0 make...
-  gcc-4.8.0 installed in /opt/local  -

Finished: symlinks are in: /opt/local/x64
  Fixing your GCC48 x64 Symlinks
  Finished: Fixing
  symlinks are in: /Users/francois/Documents/CloverGrower/toolchain/x64
..
Ready to build Clover 1747, Using Gcc 4.8.0

loverGrower V5.1f Clovermc RELEASE OK
     running ./ebuild.sh -gcc48 -ia32 -release
Initializing workspace
Loading previous configuration from $WORKSPACE/Conf/BuildEnv.sh
WORKSPACE: /Users/francois/Documents/CloverGrower/src/edk2
EDK_TOOLS_PATH: /Users/francois/Documents/CloverGrower/src/edk2/BaseTools

Running edk2 build for CloverIA32 using the command:
build  -p Clover/Clover.dsc -a IA32 -b RELEASE -t GCC48 -n 5 

Build environment: Darwin-12.3.0-x86_64-i386-64bit
Build start time: 12:45:04, May.25 2013

WORKSPACE        = /Users/francois/Documents/CloverGrower/src/edk2
ECP_SOURCE       = /Users/francois/Documents/CloverGrower/src/edk2/EdkCompatibilityPkg
EDK_SOURCE       = /Users/francois/Documents/CloverGrower/src/edk2/EdkCompatibilityPkg
EFI_SOURCE       = /Users/francois/Documents/CloverGrower/src/edk2/EdkCompatibilityPkg
EDK_TOOLS_PATH   = /Users/francois/Documents/CloverGrower/src/edk2/BaseTools

Architecture(s)  = IA32
Build target     = RELEASE
Toolchain        = GCC48

Active Platform          = /Users/francois/Documents/CloverGrower/src/edk2/Clover/Clover.dsc
Flash Image Definition   = /Users/francois/Documents/CloverGrower/src/edk2/Clover/Clover.fdf

Processing meta-data .. done!
Building ... /Users/francois/Documents/CloverGrower/src/edk2/MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf [IA32]
/bin/sh: /Users/francois/Documents/CloverGrower/toolchain/ia32/gcc: No such file or directory
make: **\* [/Users/francois/Documents/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC48/IA32/MdePkg/Library/BasePcdLibNull/BasePcdLibNull/OUTPUT/PcdLib.obj] Error 127
Building ... /Users/francois/Documents/CloverGrower/src/edk2/MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull.inf [IA32]

build.py...
 : error 7000: Failed to execute command
    make tbuild [/Users/francois/Documents/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC48/IA32/MdePkg/Library/BasePcdLibNull/BasePcdLibNull]

build.py...
 : error 7000: Failed to execute command
    make tbuild [/Users/francois/Documents/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC48/IA32/MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull]

build.py...
 : error F002: Failed to build module
    /Users/francois/Documents/CloverGrower/src/edk2/MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf [IA32, GCC48, RELEASE]
- Failed -
  Build end time: 12:45:06, May.25 2013
  Build total time: 00:00:02

CloverGrower V5.1f Cloveria32 RELEASE  ERROR!!
Good Morning.

**Comment by STLVNUB** [comment]
Ok, looking into it.

**Comment by STLVNUB** [comment]
OK fixed it

**Comment by beta992** [comment]
Thanks for the update! If you don't get a message, it should work fine now. :+1: 
EDIT: It's working fine.

Just one question: Is it possible just to build Clover for only one arch? I don't need x32 support. Is not needed to change this, but maybe it is possible for in the future? Thanks for your work btw. :)
