### ISSUE TITLE
Flawed Committer Checking Behavior

### ISSUE THREAD

**Issue by Noctem** [STLVNUB/CloverGrower#11]
I noticed that you've implemented a check for who made the last commit, and set it to ignore anyone but the main development team. That's a good idea, but unfortunately, I think the current procedure does not work as intended since it only checks the very last commit. This means that the developers can commit multiple times, but if pootle commits after that: clovergrower will ignore the changes and skip building.

For example, I'm currently at revision 1828 locally. Commits 1832-1835 were by slice2009 and blusseau, but the most recent one (1840) was by pootle. Running CloverGrower sees that 1840 was by pootle and exits, leaving me without the other new revisions from the development team. 

It seems to me that for this to be useful, it would need to check every newer revision until it finds a commit from the development team, and if it doesn't: it could be safely assumed that it should skip building.

**Comment by STLVNUB** [comment]
This is just a continuation of it's previous behaviour, which was to build latest commit.
Good idea to backtrack to last successful build revision and find one without pootle commit 
and use that to build.
Will look into it.
Thanks
