### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Taruga** [STLVNUB/CloverGrower#12]
```
 running ./ebuild.sh -gcc48 -x64 -release
```

Initializing workspace
Loading previous configuration from $WORKSPACE/Conf/BuildEnv.sh
WORKSPACE: /CloverGrower/src/edk2
EDK_TOOLS_PATH: /CloverGrower/src/edk2/BaseTools
Building tools as they are not found
make -C Source/C
Attempting to detect ARCH from 'uname -m': x86_64
Detected ARCH of X64 using uname.
mkdir -p .
make -C Common
gcc  -c -MD -fshort-wchar -fno-strict-aliasing -fno-merge-constants -nostdlib -Wall -Werror -c -g  -I .. -I ../Include/Common -I ../Include/ -I ../Include/IndustryStandard -I ../Common/ -I .. -I . -I ../Include/X64/  BasePeCoff.c -o BasePeCoff.o
clang: error: argument unused during compilation: '-fno-merge-constants'
make[2]: **\* [BasePeCoff.o] Error 1
make[1]: **\* [Common] Error 2
make: **\* [Source/C] Error 2
CloverGrower V5.3g Cloverx64_r1890 RELEASE  ERROR!!
Good Morning.

**Comment by STLVNUB** [comment]
Building on Mavericks NOT supported at this time.
