### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by FataZlity** [STLVNUB/CloverGrower#13]
make: Nothing to be done for `tbuild'.
make: **\* [/Users/fatazlity/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC48/X64/Clover/OsxBdsDxe/BdsDxe/DEBUG/BdsDxe.dll] Error 1

build.py...
 : error 7000: Failed to execute command
    make tbuild [/Users/fatazlity/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC48/X64/Clover/OsxBdsDxe/BdsDxe]

build.py...
 : error F002: Failed to build module
    /Users/fatazlity/CloverGrower/src/edk2/Clover/OsxBdsDxe/BdsDxe.inf [X64, GCC48, RELEASE]

**Comment by STLVNUB** [comment]
This is strange one, devs need to fix

**Comment by STLVNUB** [comment]
Devs fixed it
