### ISSUE TITLE
binutils error!!!!

### ISSUE THREAD

**Issue by jurijo** [STLVNUB/CloverGrower#14]
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c: In function 'dyn_string_copy':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:187: warning: implicit declaration of function 'abort'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:187: warning: incompatible implicit declaration of built-in function 'abort'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:193: warning: implicit declaration of function 'strcpy'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:193: warning: incompatible implicit declaration of built-in function 'strcpy'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c: In function 'dyn_string_copy_cstr':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:206: warning: implicit declaration of function 'strlen'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:206: warning: incompatible implicit declaration of built-in function 'strlen'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:211: warning: incompatible implicit declaration of built-in function 'strcpy'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c: In function 'dyn_string_insert':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:249: warning: incompatible implicit declaration of built-in function 'abort'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:257: warning: implicit declaration of function 'strncpy'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:257: warning: incompatible implicit declaration of built-in function 'strncpy'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c: In function 'dyn_string_insert_cstr':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:272: warning: incompatible implicit declaration of built-in function 'strlen'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:280: warning: incompatible implicit declaration of built-in function 'strncpy'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c: In function 'dyn_string_append':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:316: warning: incompatible implicit declaration of built-in function 'strcpy'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c: In function 'dyn_string_append_cstr':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:328: warning: incompatible implicit declaration of built-in function 'strlen'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:334: warning: incompatible implicit declaration of built-in function 'strcpy'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c: In function 'dyn_string_substring':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:371: warning: incompatible implicit declaration of built-in function 'abort'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c: In function 'dyn_string_eq':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/dyn-string.c:396: warning: implicit declaration of function 'strcmp'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c: In function 'fibheap_union':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:151: warning: implicit declaration of function 'free'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c: In function 'fibheap_replace_key_data':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:220: error: 'LONG_MIN' undeclared (first use in this function)
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:220: error: (Each undeclared identifier is reported only once
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:220: error: for each function it appears in.)
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c: In function 'fibheap_delete_node':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:261: error: 'LONG_MIN' undeclared (first use in this function)
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:265: warning: implicit declaration of function 'abort'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:265: warning: incompatible implicit declaration of built-in function 'abort'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c: In function 'fibheap_consolidate':
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:368: warning: implicit declaration of function 'memset'
/Users/jurij/Downloads/CloverGrower-master/toolchain/CloverTools/src/tools/gcc/binutils-2.23.2/libiberty/fibheap.c:368: warning: incompatible implicit declaration of built-in function 'memset'
make[2]: **\* [fibheap.o] Error 1
make[1]: **\* [all-libiberty] Error 2
make[1]: **\* Waiting for unfinished jobs....
make: **\* [all] Error 2

**Comment by STLVNUB** [comment]
not much info

**Comment by jurijo** [comment]
Hello

What info do you need to help me out?

Thanx

Jurij

Da: STLVNUB [mailto:notifications@github.com] 
Inviato: domenica 15 settembre 2013 01:51
A: STLVNUB/CloverGrower
Cc: jurijo
Oggetto: Re: [CloverGrower] binutils error!!!! (#14)

not much info

**Comment by STLVNUB** [comment]
Since you have trouble building GCC and I don't know what problem is
Here is link to compiled GCC4.8.1
https://dl.dropboxusercontent.com/u/81717403/x86_64-linux-gnu.zip
Unzip and place in CG/toolchain/CloverTools Folder.
Should build now.

**Comment by jurijo** [comment]
Thanx my friend,

I have merged the /bin and /lib folders of your zip file with the ones into my toolchain/CloverTools folder.

I launched CloverGrower.command but it still cannot find GCC.

What have I done wrong?

Thanx,

Jurij

Da: STLVNUB [mailto:notifications@github.com] 
Inviato: lunedì 16 settembre 2013 17:47
A: STLVNUB/CloverGrower
Cc: jurijo
Oggetto: Re: [CloverGrower] binutils error!!!! (#14)

Since you have trouble building GCC and I don't know what problem is
Here is link to compiled GCC4.8.1
https://dl.dropboxusercontent.com/u/81717403/x86_64-linux-gnu.zip
Unzip and place in CG/toolchain/CloverTools Folder.
Should build now.

**Comment by jurijo** [comment]
what's the point of closing an unsolved issue?

**Comment by STLVNUB** [comment]
Even if I fix YOUR problem, I will still need to fix the shambles that Clover has become.
I'm sorry, it's pretty pointless, I suggest you try the Pro version, as the Author is only catering for himself.
CloverGrower won't be Growing any more ( for now)
