### ISSUE TITLE
buildgcc.sh error on line 505

### ISSUE THREAD

**Issue by jabali2405** [STLVNUB/CloverGrower#17]
I'm a total noob, so maybe I'm completely wrong on this one, but when trying to execute the CloverGrower.command, after figuring out what that thing about the universal edk2 folder was supposed to mean and what I was to do to continue with the process, I got an error about an unbound variable in buildgcc.sh at line 505. I think that the issue is that the variable name is spelled with some uppercase letters where lowercase should be used: $archBIT should be $archBit. At least that's the way it is spelled in CloverGrower.command at line 18 after the export command. Changing that in buildgcc.sh at least made it work for me, I hope that the output Clover package works properly!
I hope this helps, folks. And THANK you for your work, it looks very promising, when I finally get to making Clover work for me I'll know for sure!

**Comment by STLVNUB** [comment]
Thanks, fixed.
