### ISSUE TITLE
GenFds path issues, builds failing

### ISSUE THREAD

**Issue by emory** [STLVNUB/CloverGrower#5]
hello,

There appears to be a problem with GenFds and the path it uses, I'm using a checkout from an hour ago and am a new user that hasn't successfully built Clover yet.  It originally said it can't find GenFds, so I symlinked the one from PosixLike into ~/bin/ because I didn't want to stomp on any environment variables this build command sets.

That didn't work either:

The GenFds at CloverGrower/src/edk2/BaseTools/BinWrappers/PosixLike/GenFds contains:

```
#!/usr/bin/env bash
#python `dirname $0`/RunToolFromSource.py `basename $0` $*
PYTHONPATH="`dirname $0`/../../Source/Python" \
python "`dirname $0`/../../Source/Python"/`basename $0`/`basename $0`.py $*
```

And I believe from the `cwd` of the build script that this won't work (the path isn't correct AFAICT) but I'm not sure I'm following the chain of events correctly.

Error log follows.

```
Generating DUETEFIMAINFVX64 FV
########################################


GenFds.py...
/nethome/people/emory/Projects/CloverGrower/src/edk2/Clover/HFSPlus/HFSPlus.inf(22): error 000E: File/directory not found in workspace
        /nethome/people/emory/Projects/CloverGrower/src/edk2/Clover/HFSPlus/X64/HFSPlus.efi
make: *** [fds] Error 14
###########################


build.py...
 : error 7000: Failed to execute command
        make fds [/nethome/people/emory/Projects/CloverGrower/src/edk2/Build/Clover/RELEASE_GCC47]

- Failed -
Build end time: 19:26:58, Jan.13 2013
Build total time: 00:02:04
```

**Comment by STLVNUB** [comment]
Looks to me like the HFSPLus.efi is NOT in the folder, can you check?

**Comment by emory** [comment]
I do have an HFSPlus.efi here:

```
$ find . -name HFSPlus.efi
./src/edk2/Clover/HFSPlus/ia32/HFSPlus.efi
./src/edk2/Clover/HFSPlus/x64/HFSPlus.efi
./Files/HFSPlus/x64/HFSPlus.efi
./Files/HFSPlus/ia32/HFSPlus.efi
```

**Comment by emory** [comment]
additional info:

```
$ ls -la  ./src/edk2/Clover/HFSPlus/x64/HFSPlus.efi
-rwxr-xr-x  1 emory  staff  23616 Jan 13 13:27 ./src/edk2/Clover/HFSPlus/x64/HFSPlus.efi

$ file ./src/edk2/Clover/HFSPlus/x64/HFSPlus.efi
./src/edk2/Clover/HFSPlus/x64/HFSPlus.efi: MS-DOS executable
```

**Comment by STLVNUB** [comment]
Haven't had that error before, 
did edk2 BaseTools compile successfully??, will fail if they aren't built
or delete Build folder and run again.

**Comment by emory** [comment]
presumably; when I run `make` in the BaseTools directory: 

```
Ran 234 tests in 5.352s

OK
```

**Comment by emory** [comment]
I deleted the build folder and then ran `./CloverGrower.command` again and it barfs here:

```
svn: Can't open file 'EmbeddedPkg/Include/Guid/.svn/text-base/._ExtractSection.h.svn-base': No such file or directory
```

Should I open this as a new issue against CloverGrower?  I'm just removing `src/` entirely from the top level of the project and will try that next.

**Comment by emory** [comment]
(FWIW this is a typical 10.8 system in that I have Xcode and Xcode CLI tools installed as expected but I do use HomeBrew instead of MacPorts.)

**Comment by STLVNUB** [comment]
Problem may be local. i.e your end.
Haven't had anybody else with this problem.
Try it on different HD.

**Comment by emory** [comment]
I can replicate locally when I do a build in the $cwd of the check-out.  I have successfully built Clover via CloverLoader now by selecting `/opt/local` instead.  I'm fine with using `/opt/local` but it may warrant another look?
