### ISSUE TITLE
Xcode is already installed, but command goes to developer.apple.com/xcode

### ISSUE THREAD

**Issue by Grawl** [STLVNUB/CloverGrower#6]
OS X 10.8.2 on MacBook 5,1.

**Comment by Noctem** [comment]
Did you install the Command Line Tools?

**Comment by Grawl** [comment]
Ah yes, the error is requested Command Line Tools, not just Xcode.

**Comment by STLVNUB** [comment]
Goes to that site because some users may need to register, BEFORE they can download.
Seasoned users should know what to do and where to go from there.
Unfortunately, you can't cater for everyone, and I wouldn't like to try.
Will look at it though.
